---
title: "Simulation study"
author: "Rianne"
date: "2026-05-20"
output: html_document
---

#Survival packages 
```{r}
library(ggsurvfit)
library(survival)
library(survminer)
library(ggplot2)
set.seed(42)
```

#Functions
```{r}
#Function for making the dataset
dataset <- function(n, perc_censored) {
  time_CR = rexp(n, 8)
  time_event = rexp(n, 0.1)
  event = rbinom(n, size = 1, prob = 1 - perc_censored)
  
  dataset <- data.frame(
    time_CR = time_CR,
    time_event = time_event,
    event = event,
    time_CR_to_time_event = time_event - time_CR
  )
  return(dataset)
}

#Function for simulating the missing values 
dataset_missing <- function(dataset, perc_missing) {
  missing = rbinom(nrow(dataset), size = 1, prob = perc_missing)
  dataset['missing'] = missing
  dataset$time_CR[dataset$missing == 1] = NA
  dataset$time_CR_to_time_event[dataset$missing == 1] = NA
  print(dataset)
  return(dataset)
}
```

#The method of multiple imputation
```{r}
vector_ecdf_function <- function(data, index) {
  time_CR_no_na <- data$time_CR[which(!is.na(data$time_CR) 
                  & data$time_CR <=
                    data$time_event[index])]#Values we work with
  ecdf_values <- ecdf(time_CR_no_na)(time_CR_no_na)#Store values
  vector_ecdf <- data.frame(time_CR_no_na, 
                          ecdf_values)#The dataframe of combined time & ecdf values
  vector_ecdf <- vector_ecdf[order(vector_ecdf$time_CR_no_na),]#Ordered
  rownames(vector_ecdf) <- NULL#Remove index
  
  #p_i = P(t_i)-P(t_{i-1})
  t_previous = 0
  for (t in 1:nrow(vector_ecdf)) {
    t_next <- vector_ecdf$ecdf_values[t]
    vector_ecdf$ecdf_values[t] <- t_next-t_previous
    t_previous <- t_next
  }
  vector_ecdf <- vector_ecdf[which(vector_ecdf$ecdf_values != 0),]#Remove 0 rows
  return(vector_ecdf)
}

Multiple_Imputation <- function(data) {
  #Dataframe to be filled with MI
  data_MI <- data.frame(index = which(is.na(data$time_CR)),
        time_event = data$time_event[which(is.na(data$time_CR))],
        event = data$event[which(is.na(data$time_CR))])
  
  #Big for-loop
  for (i in 1:nrow(data_MI)) {#For every missing data
    vector_ecdf <- vector_ecdf_function(data, data_MI$index[i])#Making the individual ecdf function
    for (j in 1:20) {#For every imputation
      #Fill in the time to event since complete remission
      data_MI[i,paste0("MI", j)] <- sample(vector_ecdf$time_CR_no_na, 1,
                         prob = vector_ecdf$ecdf_values)
    }#For every imputation
  }#For every missing data
  
  #Dataframe to be filled to create the full one
  observed_data <- data.frame(index = which(!is.na(data$time_CR)),
    time_event = data$time_event[which(!is.na(data$time_CR))],
    event = data$event[which(!is.na(data$time_CR))])
  #Little for-loop for making new rows
  for (i in 1:nrow(observed_data)) {#For data
    for (j in 1:20) {#For every Imputation
      observed_data[i,paste0("MI", j)] <-
            data$time_CR[observed_data[i,1]]
    }#For every Imputation
  }#For data
  data_MI_complete <- rbind(data_MI, observed_data)#The complete dataset of the imputations
  data_MI_complete <-
      data_MI_complete[order(data_MI_complete$index),]#Ordered
  rownames(data_MI_complete) <- NULL#Remove index
  
  #Making each survival function of the imputations and simultaneously constructing the average
  df <- data.frame(time = seq(0, 10, by = 0.01),#empty dataset
                   surv = rep(0, times = 1001),
                   Estimator = "Multiple Imputation")
  for (j in 0:1001) {#For every time point
    k = 0.01*j
    for (i in 1:20) {#For every imputation
      MI_var <- paste0("MI", i)
      fit <- survfit(
              as.formula(paste0("Surv(time_event - ", MI_var,", event) ~ 1")),
              data = data_MI_complete)
      df$surv[which(df$time == k)] = df$surv[which(df$time == k)]+(summary(fit, times = k)$surv / 20)
    }#For every imputation
  }#For every time point
  return(df)
}
```


#The method of Parametric approach
```{r}
#Function for the likelihood
expexp <- function(par, data_PA) {
  lambda1 = par[1]
  lambda2 = par[2]
  
  tCR = !is.na(data_PA$time_CR)
  no_tCR = is.na(data_PA$time_CR)
  
  L = length(data_PA$time_CR)* log(lambda1) 
  L = L + sum(data_PA$event) * log(lambda2)
  L = L - sum(data_PA$time_event) * lambda2
  L = L + sum(data_PA$time_CR[tCR]) * (lambda2-lambda1) 
  L = L + sum(log((exp((lambda2-lambda1)*data_PA$time_event[no_tCR])-1)/(lambda2-lambda1)))
  return(-L)
}

Parametric_approach <- function(dataset) {
  #Solving the likelihood
  solutions <- nlminb( c(8, 0.1),
    expexp,
    data_PA = dataset,
    lower = c(2, 1e-8),
    upper = c(20, 1)
  )$par
  lambda <- solutions[2]
  
  #Survival function
  x_vals <- seq(0, 10, length.out = 1001)
  y_vals <- exp(-lambda * x_vals)
  df <- data.frame(time = x_vals, surv = y_vals,
                   Estimator = "Parametric Approach")
  return(df)
}
```

#The algorithm for one simulation study with given n and percentages
```{r}
algorithm <- function(n, perc_censored, perc_missing) {
  dataset = dataset(n, perc_censored)
  fit <- survfit(Surv(time_CR_to_time_event, event) ~ 1,
                          data = dataset)#Kaplan-Meier
  fit <- summary(fit, times = seq(0, 10, length.out = 1001))
  df <- data.frame(time = fit$time, surv = fit$surv,
                   Estimator = "Simulated full dataset")
  
  #We simulate missingness
  dataset_missing = dataset_missing(dataset, perc_missing)
  
  #Apply the methods
  df_MI = Multiple_Imputation(dataset_missing)
  df_PA = Parametric_approach(dataset_missing)
  df_plot <- rbind(df, df_MI, df_PA)#combining the dataframes
  
  return(df_plot)
}
```

#Plotting one of the simulation studies
```{r}
plot <- function(n, perc_censored, perc_missing) {
  df <- algorithm(n, perc_censored, perc_missing)
  
  #Plotting
  plot <- ggplot(df, aes(time, surv, color = Estimator)) +
  geom_step()+
  labs(
    title = "Simulation study with both the MI and PA methods",
    x = "Time since complete remission (in years)",
    y = "Survival function"
    )+
  xlim(0,10)+
  ylim(0,1)+
  theme(legend.position = c(0.2, 0.2),
        legend.background = element_rect(fill = "white"))
  return(plot)
}
plot1 = plot(500, 0.5, 0.4)
print(plot1)
ggsave("one_simulationstudy.png", plot = plot1, 
         width = 6.5, height = 4, dpi = 300)
```


